//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsChessApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int Id { get; set; }
        public string Player_black_nickname { get; set; }
        public string Player_white_nickname { get; set; }
        public string Winner { get; set; }
        public string Timestamp { get; set; }
        public string Duration { get; set; }
        public string GivenTime { get; set; }
        public string Remaining_white_player { get; set; }
        public string Remaining_black_player { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
